#!/bin/sh

if [ "$1" == "--cram" ]; then
    shift
    CRAM="$1"
    shift
else
    CRAM=cram
fi

if [ "$1" == "--root" ]; then
    shift
    ROOT="$1"
    shift
else
    ROOT=$(dirname $PWD)
fi

if [ "$1" == "--tests" ]; then
    shift
    TESTS="$1"
    shift
else
    TESTS=../tests
fi

export ROOT

LD_LIBRARY_PATH="$PWD/src:$LD_LIBRARY_PATH" \
PATH="$PWD/src:$PATH" \
  "$CRAM" "$@" "$TESTS"
